import {need,keys,int,bytes,same} from './databasePreviewGuards.ts';
export const PG_LIMITS={max_input_bytes:16777216,max_toc_bytes:8388608,max_objects:1024,max_field_bytes:1048576,max_dependencies_per_object:256,max_dependencies_total:16384,max_tar_members:4096,max_label_chars:128,max_label_bytes:512};
export const PG_OBJECT_TYPES=['ACL','ACL LANGUAGE','AGGREGATE','BLOB','BLOB COMMENTS','BLOB METADATA','BLOBS','CAST','CHECK CONSTRAINT','COLLATION','COMMENT','CONSTRAINT','CONVERSION','DATABASE','DATABASE PROPERTIES','DEFAULT','DEFAULT ACL','DOMAIN','DOMAIN CONSTRAINT','ENCODING','EVENT TRIGGER','EXTENSION','FK CONSTRAINT','FOREIGN DATA WRAPPER','FOREIGN SERVER','FOREIGN TABLE','FUNCTION','INDEX','INDEX ATTACH','MATERIALIZED VIEW','MATERIALIZED VIEW DATA','OPERATOR','OPERATOR CLASS','OPERATOR FAMILY','POLICY','PROCEDURAL LANGUAGE','PROCEDURE','PUBLICATION','PUBLICATION TABLE','PUBLICATION TABLES IN SCHEMA','ROW SECURITY','RULE','SCHEMA','SEARCHPATH','SECURITY LABEL','SEQUENCE','SEQUENCE OWNED BY','SEQUENCE SET','SHELL TYPE','STATISTICS','STATISTICS DATA','STDSTRINGS','SUBSCRIPTION','SUBSCRIPTION TABLE','TABLE','TABLE ATTACH','TABLE DATA','TABLE DATA STATISTICS','TABLESPACE','TEXT SEARCH CONFIGURATION','TEXT SEARCH DICTIONARY','TEXT SEARCH PARSER','TEXT SEARCH TEMPLATE','TRANSFORM','TRIGGER','TYPE','USER MAPPING','VIEW','OTHER'];
export interface PgObject {path:string;node_type:'group';attributes:{object_type:string;schema:string;name:string}}
export const PG_PUBLIC_NAME_TYPES=['ENCODING','STDSTRINGS','SEARCHPATH','SCHEMA','TABLE','TABLE DATA','TABLE ATTACH','VIEW','MATERIALIZED VIEW','MATERIALIZED VIEW DATA','INDEX','INDEX ATTACH','CONSTRAINT','CHECK CONSTRAINT','FK CONSTRAINT','DEFAULT','FUNCTION','PROCEDURE','AGGREGATE','TRIGGER','RULE','TYPE','SHELL TYPE','DOMAIN','DOMAIN CONSTRAINT','SEQUENCE','SEQUENCE SET','SEQUENCE OWNED BY','STATISTICS','STATISTICS DATA','TABLE DATA STATISTICS','COLLATION','CONVERSION','OPERATOR','OPERATOR CLASS','OPERATOR FAMILY','TEXT SEARCH CONFIGURATION','TEXT SEARCH DICTIONARY','TEXT SEARCH PARSER','TEXT SEARCH TEMPLATE'];
export interface PgDumpData {format:string;container:string;archiveVersion:string;sourceBytes:number;objects:PgObject[]}
const label=(s:unknown):s is string=>typeof s==='string'&&Array.from(s).length>=1&&Array.from(s).length<=128&&bytes(s)<=512&&s===s.trim()&&/^[\p{L}\p{N}_ .()@,+-]+$/u.test(s);
export function parsePgDump(payload:unknown,metadata:unknown):PgDumpData{
  keys(payload,'view_kind media_type tree choices selected');need(payload.view_kind==='tree'&&payload.media_type==='application/json');keys(payload.choices,'');keys(payload.selected,'');
  keys(metadata,'engine format container archive_version source_bytes input_mode objects_returned objects_total data_verified limits');
  const m=metadata;need(m.engine==='pg-dump'&&m.input_mode==='whole'&&['pgdump','dump','backup','tar'].includes(m.format)&&['PostgreSQL custom archive','PostgreSQL tar archive'].includes(m.container)&&['1.14.0','1.15.0','1.16.0'].includes(m.archive_version)&&int(m.source_bytes,64,16777216)&&m.data_verified===false&&same(m.limits,PG_LIMITS));
  need(Array.isArray(payload.tree)&&payload.tree.length>=1&&payload.tree.length<=1024&&int(m.objects_returned,payload.tree.length,payload.tree.length)&&int(m.objects_total,payload.tree.length,payload.tree.length));
  for(const n of payload.tree){keys(n,'path node_type attributes');need(typeof n.path==='string'&&n.path.length===27&&/^\/o-[0-9a-f]{24}$/.test(n.path)&&n.node_type==='group');keys(n.attributes,'object_type schema name');need(PG_OBJECT_TYPES.includes(n.attributes.object_type)&&label(n.attributes.schema)&&label(n.attributes.name));if(!PG_PUBLIC_NAME_TYPES.includes(n.attributes.object_type))need(n.attributes.name==='名称已隐藏'&&n.attributes.schema==='无命名空间')}
  need(new Set(payload.tree.map(n=>n.path)).size===payload.tree.length&&bytes(JSON.stringify({payload,metadata}))<=2097152);
  return {format:m.format,container:m.container,archiveVersion:m.archive_version,sourceBytes:m.source_bytes,objects:payload.tree};
}
