"""Atomic storage contract for one original analysis request's private ledger."""
from typing import Protocol


class AnalysisBudgetRepository(Protocol):
    async def get(self, lineage_id: str) -> dict | None: ...

    async def create_if_absent(self, document: dict) -> dict: ...

    async def compare_and_swap(self, lineage_id: str, version: int, document: dict, *, require_before_deadline: bool = False) -> bool: ...

    async def reserve_operation(self, document: dict) -> tuple[dict, bool]: ...

    async def aggregate_usage(self, lineage_id: str, user_id: str, session_id: str) -> dict: ...

    async def settle_operation(self, operation_id: str, lineage_id: str, user_id: str,
                               session_id: str, actual_tokens: int | None) -> dict | None: ...
