from datetime import datetime
from typing import Protocol

from app.domain.models.event import MessageEvent
from app.domain.models.input_admission import AcceptedInput


class InputRepository(Protocol):
    async def accept(self, session_id: str, actor_user_id: str, event: MessageEvent, *, generation: int | None = None) -> AcceptedInput | None: ...
    async def get(self, session_id: str, key: str) -> AcceptedInput | None: ...
    async def claim(self, record: AcceptedInput, runtime_id: str, expires: datetime) -> AcceptedInput | None: ...
    async def transition(self, record: AcceptedInput, updates: dict, *, require_live: bool = False) -> AcceptedInput | None: ...
    async def candidates(self, now: datetime, limit: int = 100) -> list[AcceptedInput]: ...
    async def terminal_kind(self, record: AcceptedInput) -> str | None: ...
    async def authorized(self, record: AcceptedInput) -> bool: ...
    async def cancel_session(self, session_id: str) -> None: ...
    async def disable_session(self, session_id: str) -> None: ...
    async def unsettled(self, session_id: str) -> AcceptedInput | None: ...
    async def latest(self, session_id: str) -> AcceptedInput | None: ...
    async def matches_terminal(self, session_id: str, key: str, seq: int, kind: str) -> bool: ...
    async def generation(self, session_id: str) -> int: ...
