import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
import * as vue from 'vue';
import {compileScript,parse} from '@vue/compiler-sfc';
import ts from 'typescript';
import {usePreviewLoad} from '../src/composables/usePreviewLoad.ts';
import * as identity from '../src/visualizations/previewIdentity.ts';
import * as helpers from '../src/visualizations/extended/astronomyWorkbenchData.ts';
const fixtures=JSON.parse(readFileSync(new URL('./browser/main-astronomy-data.json',import.meta.url),'utf8')),version='a'.repeat(64);
const flush=async()=>{for(let i=0;i<40;i++)await Promise.resolve();await vue.nextTick();};
const pending=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};};
function result(key='tree') {const {contract_version,type,reader,metadata,warnings,sampled,kind,...payload}=structuredClone(fixtures[key]);return {contract_version,kind:kind==='image'?'raster':kind,plugin_id:'viz-astronomy-workbench',version,revision:'b'.repeat(64),metadata,warnings,sampled,payload:{...payload,view_kind:kind}};}
const parsed=key=>{const r=result(key);return helpers.parseAstronomyWorkbench(fixtures[key].kind,r.payload,r.metadata,fixtures[key].selected);};
for(const key of Object.keys(fixtures))test(`actual producer payload ${key} accepted`,()=>assert.ok(parsed(key)));
test('spectrum nulls split segments without artificial bridging',()=>{assert.deepEqual(helpers.astronomySpectrumSegments([0,1,2,3],[1,2,null,5]),['0,400 333.3333333333333,305','1000,20']);assert.deepEqual(helpers.astronomySpectrumSegments([0],[null]),[]);});
const mutations=[['root URL',r=>r.payload.url='https://invalid'],['metadata path',r=>r.metadata.path='/Users/private/a'],['byte budget',r=>r.metadata.source_bytes=33554433],['limits bool',r=>r.metadata.limits.datasets=true],['wrong shape',r=>r.payload.choices.datasets[0].plane_shape=[6,4]],['shape bool',r=>r.payload.choices.datasets[0].shape=[true,4,6]],['wrong slice',r=>r.payload.selected.slices=[0]],['no selected slice',r=>r.payload.selected.slices=[]],['kind',r=>r.payload.view_kind='geometry'],['source name URL',r=>r.payload.choices.datasets[0].name='file:///tmp/a'],['unknown image field',r=>r.payload.workbench.source='/etc/passwd'],['image dimensions',r=>r.payload.workbench.render_width=7],['image URL',r=>r.payload.workbench.image_base64='https://invalid'],['PNG dimensions',r=>r.payload.workbench.render_height=3],['stats count',r=>r.payload.workbench.statistics.valid_count=24],['histogram NaN',r=>r.payload.workbench.histogram.edges[0]=NaN],['histogram count',r=>r.payload.workbench.histogram.counts[0]=500001],['manual equal',r=>{r.payload.selected.interval='manual';r.payload.selected.low=r.payload.selected.high=1;}],['WCS Infinity',r=>r.payload.workbench.wcs.corners[0][0]=Infinity]];
for(const [name,mutate] of mutations)test(`render rejects ${name}`,()=>{const r=result('render');mutate(r);assert.throws(()=>helpers.parseAstronomyWorkbench('image',r.payload,r.metadata,fixtures.render.selected));});
for(const options of [{...fixtures.pixel.selected,dataset:true},{...fixtures.pixel.selected,x:-1},{...fixtures.render.selected,interval:'manual',low:2,high:1},{...fixtures.sources.selected,threshold_sigma:51},{...fixtures.region.selected,bounds:[0,0,0,1]},{...fixtures.pixel.selected,url:'file:///tmp/a'}])test(`bad options ${JSON.stringify(options)}`,()=>assert.throws(()=>helpers.validateAstronomyOptions('image',options)));
function mount(t,response=req=>result(req.kind==='image'?req.action:req.kind)){
 const seen=[];const modules={vue,'../../composables/usePreviewLoad':{usePreviewLoad},'../previewIdentity':identity,'./astronomyWorkbenchData':helpers,'./domains/lifecycle':{displayError:e=>e.message},'../runtime':{requestVisualization:async(file,plugin,operation,req,signal)=>{seen.push({file:structuredClone(vue.toRaw(file)),request:req,signal});return response(req);}}};
 const source=readFileSync(new URL('../src/visualizations/extended/AstronomyWorkbenchPreview.vue',import.meta.url),'utf8'),compiled=ts.transpileModule(compileScript(parse(source).descriptor,{id:'astronomy'}).content,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 const module={exports:{}};new Function('require','module','exports',compiled)(id=>{assert.ok(id in modules,id);return modules[id];},module,module.exports);
 const props=vue.reactive({file:{file_id:'file-a',filename:'synthetic.fits',size:fixtures.tree.metadata.source_bytes,metadata:{dataset_file_version:'v1'}},plugin:{id:'viz-astronomy-workbench',version:'1',adapter:'astronomy-workbench',reader:'astronomy-workbench',enabled:true,capabilities:{operations:['preview'],input_mode:'whole',shared:false},limits:{max_input_bytes:33554432,max_output_bytes:4194304}}});
 const scope=vue.effectScope(),state=scope.run(()=>module.exports.default.setup(props,{expose(){}}));t.after(()=>scope.stop());return {props,state,seen,stop:()=>scope.stop()};
}
function select(v){v.state.slices.value=[1];v.state.stretch.value='asinh';v.state.colour.value='heat';}
test('actual Vue keeps tree first and pins all image operations to source version',async t=>{const v=mount(t);await flush();assert.equal(v.seen.length,1);assert.equal(v.state.error.value,'');assert.equal(v.state.rendered.value,undefined);select(v);await v.state.execute('image',fixtures.render.selected);assert.equal(v.state.error.value,'');assert.equal(v.seen[1].request.version,version);assert.equal(v.state.rendered.value.width,6);await v.state.execute('image',fixtures.pixel.selected);assert.equal(v.state.pixel.value.value,32);assert.equal(v.state.rendered.value.width,6);await v.state.execute('image',fixtures.region.selected);assert.equal(v.state.region.value.pixel_count,6);await v.state.execute('image',fixtures.sources.selected);assert.ok(v.state.sources.value);});
test('display and dataset changes purge old image and preserve stable metadata clones',async t=>{const v=mount(t);await flush();select(v);await v.state.execute('image',fixtures.render.selected);const count=v.seen.length;v.props.file=structuredClone(vue.toRaw(v.props.file));v.props.plugin=structuredClone(vue.toRaw(v.props.plugin));await flush();assert.equal(v.seen.length,count);v.state.colour.value='gray';assert.equal(v.state.rendered.value,undefined);v.state.dataset.value=1;await v.state.execute('table',fixtures.table.selected);assert.equal(v.state.table.value.rows.length,2);v.state.dataset.value=2;await v.state.execute('series',fixtures.series.selected);assert.equal(v.state.spectrum.value.values[2],null);assert.equal(v.state.table.value,undefined);});
test('FITS gzip filename keeps opaque ID and canonical fits metadata, without client decompression',async t=>{const v=mount(t);await flush();v.props.file.filename='synthetic.fits.gz';await flush();select(v);await v.state.execute('image',fixtures.render.selected);assert.equal(v.state.error.value,'');assert.equal(v.state.catalog.value.format,'fits');assert.equal(v.seen[v.seen.length-1].file.filename,'synthetic.fits.gz');assert.equal(v.seen[v.seen.length-1].file.file_id,'file-a');assert.equal(v.seen[v.seen.length-1].request.version,version);});
for(const action of ['disable','unmount','slice','file','limits','cancel','display'])test(`late raster after ${action} cannot revive`,async t=>{const wait=pending(),v=mount(t,req=>req.kind==='tree'?result():wait.promise);await flush();select(v);const running=v.state.execute('image',fixtures.render.selected);await flush();if(action==='disable')v.props.plugin.enabled=false;else if(action==='unmount')v.stop();else if(action==='slice')v.state.slices.value=[0];else if(action==='file')v.props.file.file_id='file-b';else if(action==='limits')v.props.plugin.limits.max_input_bytes--;else if(action==='display')v.state.invert.value=true;else v.state.cancel();assert.equal(v.seen[1].signal.aborted,true);wait.resolve(result('render'));await running;assert.equal(v.state.rendered.value,undefined);});
for(const change of ['version','kind','dataset','source','choices'])test(`Vue rejects changed ${change}`,async t=>{const v=mount(t,req=>{const r=result(req.kind==='tree'?'tree':'render');if(req.kind!=='tree'){if(change==='version')r.version='c'.repeat(64);if(change==='kind')r.kind='media';if(change==='dataset')r.payload.selected.dataset=2;if(change==='source')r.metadata.source_bytes++;if(change==='choices')r.payload.choices.datasets[0].name='Different';}return r;});await flush();select(v);await v.state.execute('image',fixtures.render.selected);assert.ok(v.state.error.value);assert.equal(v.state.rendered.value,undefined);});
