import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
import * as vue from 'vue';
import ts from 'typescript';
import * as data from '../src/visualizations/extended/sequenceBrowserData.ts';
import {usePreviewLoad} from '../src/composables/usePreviewLoad.ts';
import * as identity from '../src/visualizations/previewIdentity.ts';
const fixtures=JSON.parse(readFileSync(new URL('./browser/main-bio-data.json',import.meta.url),'utf8'));
const version='a'.repeat(64),revision='b'.repeat(64);
const modes={'sequence-browser':'fasta','genome-tracks':'bed','blast-hits':'blast13'};
function envelope(key){const {reader,type,kind:view_kind,contract_version,metadata,warnings,sampled,...payload}=structuredClone(fixtures[key]);return {plugin_id:`viz-${reader}`,contract_version,version,revision,metadata,warnings,sampled,kind:view_kind==='map'?'features':view_kind,payload:{...payload,view_kind}};}
function parse(key){const source=fixtures[key];return data.parseBioData(envelope(key),source.reader,source.kind,source.selected,source.metadata.source_bytes,`x.${source.metadata.format}`);}
for(const key of Object.keys(fixtures))test(`${key} real sandbox payload parses`,()=>assert.equal(parse(key).reader,fixtures[key].reader));
for(const [mode,key] of Object.entries(modes)){
 test(`${mode} tree/data catalog identity`,()=>assert.equal(data.bioCatalogIdentity(parse(key)),data.bioCatalogIdentity(parse(key+'_tree'))));
 for(const [what,change] of Object.entries({plugin:r=>r.plugin_id='other',kind:r=>r.kind='array',contract:r=>r.contract_version=1,version:r=>r.version='',revision:r=>r.revision='bad',extra:r=>r.payload.url='https://evil',selected:r=>r.payload.selected={},metadata:r=>r.metadata.path='/Users/private',source:r=>r.metadata.source_bytes=0,limits:r=>r.metadata.limits={},format:r=>r.metadata.format='exe',sampled:r=>r.sampled=true,warnings:r=>r.warnings=[]}))test(`${mode} rejects ${what}`,()=>{const r=envelope(key);change(r);assert.throws(()=>data.parseBioData(r,mode,fixtures[key].kind,fixtures[key].selected,undefined,undefined,`viz-${mode}`));});
 for(const source of ['filename','size'])test(`${mode} rejects wrong ${source}`,()=>assert.throws(()=>data.parseBioData(envelope(key),mode,fixtures[key].kind,fixtures[key].selected,source==='size'?1:undefined,source==='filename'?'wrong.exe':undefined)));
}
test('sequence window shows positions, uppercase motif and per-base Phred',()=>{const d=parse('fastq'),bases=data.sequenceBases(d);assert.equal(bases[0].position,1);assert.deepEqual(bases.map(x=>x.quality),[0,20,30,40,41,42]);assert.equal(data.sequenceBases(parse('fasta_search')).filter(x=>x.hit).length,38);});
test('BLAST small E-values remain strings, no invented coverage, reverse ranges',()=>{const d=parse('blast12'),reverse=d.hits.rows[1],r=data.blastRange(reverse,d.queries[reverse.query]);assert.equal(d.hits.rows[0].evalue,'1e-350');assert.equal(reverse.coverage,null);assert.deepEqual(r,{left:.75,width:.25,reverse:true,knownLength:false});const single=d.hits.rows[2];assert.equal(data.blastRange(single,d.queries[single.query]).width,1);});
test('BLAST qlen coverage is real inclusive span',()=>assert.equal(parse('blast13').hits.rows[0].coverage,10));
test('chromosome tracks use 0-based half-open positions without filling signal gaps',()=>{assert.deepEqual(parse('gff').tracks.map(f=>[f.start,f.end,f.strand]),[[0,20,'-']]);assert.deepEqual(parse('bedgraph').tracks.map(f=>[f.start,f.end,f.value]),[[0,10,4],[20,30,-2]]);assert.equal(parse('bed').tracks[2].start,parse('bed').tracks[2].end);});
test('object key ordering does not change selection trust or catalog identity',()=>{const r=envelope('fasta');r.payload.selected=Object.fromEntries(Object.entries(r.payload.selected).reverse());assert.equal(data.bioCatalogIdentity(data.parseBioData(r,'sequence-browser','table',fixtures.fasta.selected)),data.bioCatalogIdentity(parse('fasta')));});
for(const [key,change] of [['fasta',r=>r.payload.sequence.bases='evil'],['fastq',r=>r.payload.sequence.qualities[0]=-1],['fasta_search',r=>r.payload.sequence.search.positions[0]=2],['bed',r=>r.payload.tracks[0].start=-1],['bed',r=>r.payload.tracks[0].track='variant'],['blast13',r=>r.payload.hits.rows[0].coverage=100],['blast12',r=>r.payload.hits.rows[0].coverage=100]])test(`${key} rejects scientific mutation ${change}`,()=>{const r=envelope(key);change(r);assert.throws(()=>data.parseBioData(r,fixtures[key].reader,fixtures[key].kind,fixtures[key].selected));});
const flush=async()=>{for(let i=0;i<60;i++)await Promise.resolve();await vue.nextTick();};
const pending=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};};
function mount(t,mode,request){const key=modes[mode],seen=[],modules={vue,'../../composables/usePreviewLoad':{usePreviewLoad},'../previewIdentity':identity,'../runtime':{requestVisualization:async(f,p,op,o,signal)=>{seen.push({o,signal});return request?request(o,signal):envelope(o.kind==='tree'?key+'_tree':key);}},'./domains/lifecycle':{displayError:e=>e.message},'./sequenceBrowserData':data};
 const text=readFileSync(new URL('../src/visualizations/extended/useBioPreview.ts',import.meta.url),'utf8'),module={exports:{}};new Function('require','module','exports',ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>{assert.ok(name in modules,name);return modules[name];},module,module.exports);
 const props=vue.reactive({file:{file_id:'opaque',filename:`x.${fixtures[key].metadata.format}`,size:fixtures[key].metadata.source_bytes},plugin:{id:`viz-${mode}`,enabled:true,version:'1.0.0',capabilities:{operations:['preview'],shared:false,input_mode:'whole'}}});const scope=vue.effectScope(),state=scope.run(()=>module.exports.useBioPreview(()=>props.file,()=>props.plugin,mode));t.after(()=>scope.stop());return {props,scope,state,seen};
}
for(const [mode,key] of Object.entries(modes)){
 test(`${mode} tree first and explicit version-pinned data only`,async t=>{const v=mount(t,mode);await flush();assert.deepEqual(v.seen[0].o,{kind:'tree'});assert.equal(v.state.displayed.value,undefined);await v.state.loadData(fixtures[key].selected);assert.equal(v.state.error.value,'');assert.ok(v.state.displayed.value);assert.deepEqual(v.seen[1].o,{kind:fixtures[key].kind,version,...fixtures[key].selected});v.props.file=structuredClone(vue.toRaw(v.props.file));v.props.plugin=structuredClone(vue.toRaw(v.props.plugin));await flush();assert.equal(v.seen.length,2);assert.ok(v.state.displayed.value);});
 for(const action of ['unmount','disable','file','selection'])test(`${mode} ${action} cancels late data`,async t=>{const p=pending(),v=mount(t,mode,o=>o.kind==='tree'?envelope(key+'_tree'):p.promise);await flush();const waiting=v.state.loadData(fixtures[key].selected);await flush();const req=v.seen.at(-1);if(action==='unmount')v.scope.stop();else if(action==='disable')v.props.plugin.enabled=false;else if(action==='file')v.props.file.file_id='other';else v.state.clear();await flush();assert.equal(req.signal.aborted,true);p.resolve(envelope(key));await waiting;assert.equal(v.state.displayed.value,undefined);});
 for(const changed of ['version','catalog','selection'])test(`${mode} changed ${changed} refused`,async t=>{const v=mount(t,mode,o=>{const r=envelope(o.kind==='tree'?key+'_tree':key);if(o.kind!=='tree'){if(changed==='version')r.version='c'.repeat(64);if(changed==='catalog')r.metadata.labels_redacted++;if(changed==='selection')r.payload.selected={};}return r;});await flush();await v.state.loadData(fixtures[key].selected);assert.ok(v.state.error.value);assert.equal(v.state.displayed.value,undefined);});
}
