import { defineAsyncComponent, markRaw, type Component } from 'vue';
import type { VisualizationAdapter } from './contract';

// Build-time trusted capability bindings. Manifest strings never become import URLs,
// iframe sources, API destinations, executable code, or arbitrary component props.
const trustedAdapters: Record<VisualizationAdapter, Component> = {
  image: markRaw(defineAsyncComponent(() => import('../components/filePreviews/ImageFilePreview.vue'))),
  tiff: markRaw(defineAsyncComponent(() => import('../components/filePreviews/TiffFilePreview.vue'))),
  shapefile: markRaw(defineAsyncComponent(() => import('../components/filePreviews/ShapefilePreview.vue'))),
  molecular: markRaw(defineAsyncComponent(() => import('../components/filePreviews/MolecularStructurePreview.vue'))),
  obj: markRaw(defineAsyncComponent(() => import('../components/filePreviews/ObjFilePreview.vue'))),
  html: markRaw(defineAsyncComponent(() => import('../components/filePreviews/HtmlFilePreview.vue'))),
  markdown: markRaw(defineAsyncComponent(() => import('../components/filePreviews/MarkdownFilePreview.vue'))),
  text: markRaw(defineAsyncComponent(() => import('../components/filePreviews/CodeFilePreview.vue'))),
  csv: markRaw(defineAsyncComponent(() => import('../components/filePreviews/CsvFilePreview.vue'))),
  'scientific-map': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'scientific-series': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'scientific-image': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'scientific-quality': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'plotly': markRaw(defineAsyncComponent(() => import('./extended/scientific/PlotlyPreview.vue'))),
  'h5web': markRaw(defineAsyncComponent(() => import('./extended/scientific/H5WebPreview.vue'))),
  'vtk': markRaw(defineAsyncComponent(() => import('./extended/scientific/VtkPreview.vue'))),
  'jsroot': markRaw(defineAsyncComponent(() => import('./extended/scientific/JsRootPreview.vue'))),
  'rdkit': markRaw(defineAsyncComponent(() => import('./extended/ScientificImagePreview.vue'))),
  'molstar': markRaw(defineAsyncComponent(() => import('./extended/scientific/MolstarPreview.vue'))),
  'nmrium': markRaw(defineAsyncComponent(() => import('./extended/scientific/NmriumPreview.vue'))),
  'openlayers': markRaw(defineAsyncComponent(() => import('./extended/domains/OpenLayersPreview.vue'))),
  'maplibre': markRaw(defineAsyncComponent(() => import('./extended/domains/DeckMapPreview.vue'))),
  'cesium': markRaw(defineAsyncComponent(() => import('./extended/domains/CesiumPreview.vue'))),
  'aladin': markRaw(defineAsyncComponent(() => import('./extended/domains/AladinPreview.vue'))),
  'metpy': markRaw(defineAsyncComponent(() => import('./extended/ScientificImagePreview.vue'))),
  'igv': markRaw(defineAsyncComponent(() => import('./extended/domains/IgvPreview.vue'))),
  'viv': markRaw(defineAsyncComponent(() => import('./extended/domains/VivPreview.vue'))),
  'niivue': markRaw(defineAsyncComponent(() => import('./extended/domains/NiivuePreview.vue'))),
  'fastqc': markRaw(defineAsyncComponent(() => import('./extended/FastQcPreview.vue'))),
  'pdfjs': markRaw(defineAsyncComponent(() => import('./extended/DocumentPreview.vue'))),
  'word': markRaw(defineAsyncComponent(() => import('./extended/DocumentPreview.vue'))),
  'excel': markRaw(defineAsyncComponent(() => import('./extended/ExcelPreview.vue'))),
  'powerpoint': markRaw(defineAsyncComponent(() => import('./extended/DocumentPreview.vue'))),
  'docx': markRaw(defineAsyncComponent(() => import('./extended/DocxPreview.vue'))),
  'onlyoffice': markRaw(defineAsyncComponent(() => import('./extended/OnlyOfficePreview.vue'))),
};
export const getVisualizationAdapter = (adapter: VisualizationAdapter): Component | null => trustedAdapters[adapter] ?? null;
