import { defineAsyncComponent, markRaw, type Component } from 'vue';
import type { VisualizationAdapter } from './contract';

// Build-time trusted capability bindings. Manifest strings never become import URLs,
// iframe sources, API destinations, executable code, or arbitrary component props.
const trustedAdapters: Record<VisualizationAdapter, Component> = {
  image: markRaw(defineAsyncComponent(() => import('../components/filePreviews/ImageFilePreview.vue'))),
  tiff: markRaw(defineAsyncComponent(() => import('../components/filePreviews/TiffFilePreview.vue'))),
  shapefile: markRaw(defineAsyncComponent(() => import('../components/filePreviews/ShapefilePreview.vue'))),
  molecular: markRaw(defineAsyncComponent(() => import('../components/filePreviews/MolecularStructurePreview.vue'))),
  obj: markRaw(defineAsyncComponent(() => import('../components/filePreviews/ObjFilePreview.vue'))),
  html: markRaw(defineAsyncComponent(() => import('../components/filePreviews/HtmlFilePreview.vue'))),
  markdown: markRaw(defineAsyncComponent(() => import('../components/filePreviews/MarkdownFilePreview.vue'))),
  text: markRaw(defineAsyncComponent(() => import('../components/filePreviews/CodeFilePreview.vue'))),
  csv: markRaw(defineAsyncComponent(() => import('../components/filePreviews/CsvFilePreview.vue'))),
  'scientific-map': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'scientific-series': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'scientific-image': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'scientific-quality': markRaw(defineAsyncComponent(() => import('./ScientificFilePreview.vue'))),
  'v2-plotly': markRaw(defineAsyncComponent(() => import('./extended/scientific/PlotlyPreview.vue'))),
  'v2-h5web': markRaw(defineAsyncComponent(() => import('./extended/scientific/H5WebPreview.vue'))),
  'v2-vtk': markRaw(defineAsyncComponent(() => import('./extended/scientific/VtkPreview.vue'))),
  'v2-jsroot': markRaw(defineAsyncComponent(() => import('./extended/scientific/JsRootPreview.vue'))),
  'v2-rdkit': markRaw(defineAsyncComponent(() => import('./extended/ScientificImagePreview.vue'))),
  'v2-molstar': markRaw(defineAsyncComponent(() => import('./extended/scientific/MolstarPreview.vue'))),
  'v2-nmrium': markRaw(defineAsyncComponent(() => import('./extended/scientific/NmriumPreview.vue'))),
  'v2-openlayers': markRaw(defineAsyncComponent(() => import('./extended/domains/OpenLayersPreview.vue'))),
  'v2-maplibre': markRaw(defineAsyncComponent(() => import('./extended/domains/DeckMapPreview.vue'))),
  'v2-cesium': markRaw(defineAsyncComponent(() => import('./extended/domains/CesiumPreview.vue'))),
  'v2-aladin': markRaw(defineAsyncComponent(() => import('./extended/domains/AladinPreview.vue'))),
  'v2-metpy': markRaw(defineAsyncComponent(() => import('./extended/ScientificImagePreview.vue'))),
  'v2-igv': markRaw(defineAsyncComponent(() => import('./extended/domains/IgvPreview.vue'))),
  'v2-viv': markRaw(defineAsyncComponent(() => import('./extended/domains/VivPreview.vue'))),
  'v2-niivue': markRaw(defineAsyncComponent(() => import('./extended/domains/NiivuePreview.vue'))),
  'v2-fastqc': markRaw(defineAsyncComponent(() => import('./extended/FastQcPreview.vue'))),
  'v2-pdfjs': markRaw(defineAsyncComponent(() => import('./extended/DocumentPreview.vue'))),
  'v2-word': markRaw(defineAsyncComponent(() => import('./extended/DocumentPreview.vue'))),
  'v2-excel': markRaw(defineAsyncComponent(() => import('./extended/ExcelPreview.vue'))),
  'v2-powerpoint': markRaw(defineAsyncComponent(() => import('./extended/DocumentPreview.vue'))),
};
export const getVisualizationAdapter = (adapter: VisualizationAdapter): Component | null => trustedAdapters[adapter] ?? null;
